name: BVT
on: [pull_request]
jobs:
  make:
    name: Make
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Make
        run: |
          make deps
          make
          make -C example deps
          make -C example
          make -C ttrpc-codegen deps
          make -C ttrpc-codegen

  clippy_check:
    name: Clippy Check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
      - uses: actions/checkout@v3
      - run: rustup component add clippy
      - uses: tim-actions/clippy-check@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: checks-${{ matrix.os }}

  # deny:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       checks:
  #         - advisories
  #         - bans sources

  #   # Prevent sudden announcement of a new advisory from failing ci:
  #   continue-on-error: ${{ matrix.checks == 'advisories' }}

  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: EmbarkStudios/cargo-deny-action@v1
  #       with:
  #         command: check ${{ matrix.checks }}
