name: BVT
on: [pull_request]
jobs:
  check:
    name: Check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check
        run: |
          make deps
          make check
          make -C compiler check
          make -C ttrpc-codegen check

  make:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: |
          make deps
          make
          make -C compiler
          make -C ttrpc-codegen
          make -C example build-examples

  # Windows doesn't have async enabled currently, so can't test all features        
  clippy_windows_check:
    name: Clippy Check
    runs-on:  windows-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup component add clippy
      - uses: tim-actions/clippy-check@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: checks-${{ matrix.os }}

  deny:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        checks:
          - advisories
          - bans sources

    # Prevent sudden announcement of a new advisory from failing ci:
    continue-on-error: ${{ matrix.checks == 'advisories' }}

    steps:
      - uses: actions/checkout@v3
      - uses: EmbarkStudios/cargo-deny-action@v1
        with:
          command: check ${{ matrix.checks }}
